import { GAME_CONFIG } from "./config";

export type Answer = { rank: number; answer: string; points: number; aliases: string[] };
export type Feud = { id: number; round: number; category: string; prompt: string; answers: Answer[] };

type Raw = [string, string[]?];
function build(id: number, category: string, prompt: string, raw: Raw[]): Feud {
  return {
    id,
    round: id,
    category,
    prompt,
    answers: raw.map(([answer, aliases = []], i) => ({
      rank: i + 1,
      answer,
      points: GAME_CONFIG.rankPoints[i] ?? 10,
      aliases,
    })),
  };
}

// Source: "The Anime Feud — Final 10 Rounds" question bank.
export const FEUDS: Feud[] = [
  build(1, "MOST OVERRATED ANIME", "Name an anime that people consider overrated.", [
    ["Demon Slayer", ["Demon Slayer: Kimetsu no Yaiba", "Kimetsu no Yaiba", "KNY"]],
    ["Jujutsu Kaisen", ["JJK"]],
    ["My Hero Academia", ["MHA", "Boku no Hero Academia", "BNHA"]],
    ["Sword Art Online", ["SAO"]],
    ["Tokyo Revengers", []],
    ["Boruto", ["Boruto: Naruto Next Generations"]],
    ["Fairy Tail", []],
    ["The Seven Deadly Sins", ["Seven Deadly Sins", "Nanatsu no Taizai", "7DS"]],
    ["Dragon Ball Z", ["DBZ", "Dragon Ball"]],
    ["Black Clover", []],
  ]),
  build(2, "MOST ICONIC ANIME OPENING", "Name an anime with the most iconic opening.", [
    ["Attack on Titan", ["AOT", "Shingeki no Kyojin", "SNK"]],
    ["Naruto", ["Naruto Shippuden"]],
    ["One Piece", ["OP"]],
    ["Death Note", []],
    ["Jujutsu Kaisen", ["JJK"]],
    ["Demon Slayer", ["Kimetsu no Yaiba", "KNY"]],
    ["Tokyo Ghoul", []],
    ["Bleach", []],
    ["Fullmetal Alchemist: Brotherhood", ["FMAB", "FMA", "Fullmetal Alchemist"]],
    ["Oshi no Ko", []],
  ]),
  build(3, "MOST ANNOYING PROTAGONIST", "Name the most annoying anime protagonist.", [
    ["Boruto — Boruto: Naruto Next Generations", []],
    ["Asta — Black Clover", []],
    ["Takemichi — Tokyo Revengers", ["Takemichi Hanagaki"]],
    ["Zenitsu — Demon Slayer", ["Zenitsu Agatsuma"]],
    ["Yukiteru — Future Diary", ["Yuki", "Yukiteru Amano", "Mirai Nikki"]],
    ["Shinji — Neon Genesis Evangelion", ["Shinji Ikari"]],
    ["Eren — Attack on Titan", ["Eren Yeager", "Eren Jaeger"]],
    ["Meliodas — The Seven Deadly Sins", []],
    ["Subaru — Re:Zero", ["Subaru Natsuki"]],
    ["Takumi — Nana", []],
  ]),
  build(4, "MOST SATISFYING ANIME REVENGE", "Name the character with the most satisfying revenge.", [
    ["Thorfinn — Vinland Saga", []],
    ["Eren — Attack on Titan", ["Eren Yeager", "Eren Jaeger"]],
    ["Sasuke — Naruto", ["Sasuke Uchiha"]],
    ["Kurapika — Hunter × Hunter", []],
    ["Guts — Berserk", []],
    ["Lelouch — Code Geass", ["Lelouch Lamperouge", "Lelouch vi Britannia"]],
    ["Light — Death Note", ["Light Yagami"]],
    ["Killua — Hunter × Hunter", ["Killua Zoldyck"]],
    ["Tanjiro — Demon Slayer", ["Tanjiro Kamado"]],
    ["Gabimaru — Hell's Paradise", []],
  ]),
  build(5, "MOST FRUSTRATING CHARACTER DEATH", "Name the most frustrating character death.", [
    ["Ace — One Piece", ["Portgas D. Ace", "Portgas Ace"]],
    ["Jiraiya — Naruto", []],
    ["Maes Hughes — Fullmetal Alchemist", ["Hughes"]],
    ["Rengoku — Demon Slayer", ["Kyojuro Rengoku"]],
    ["Erwin — Attack on Titan", ["Erwin Smith"]],
    ["Itachi — Naruto", ["Itachi Uchiha"]],
    ["Nobara — Jujutsu Kaisen", ["Nobara Kugisaki"]],
    ["Neji — Naruto", ["Neji Hyuga"]],
    ["Kamina — Gurren Lagann", []],
    ["Koro-sensei — Assassination Classroom", ["Korosensei"]],
  ]),
  build(6, "BEST ANIME RIVALS", "Name the best rivalry in anime.", [
    ["Goku vs Vegeta — Dragon Ball", []],
    ["Naruto vs Sasuke — Naruto", []],
    ["Gintoki vs Takasugi — Gintama", []],
    ["Gon vs Hisoka — Hunter × Hunter", []],
    ["Deku vs Bakugo — My Hero Academia", ["Midoriya vs Bakugo"]],
    ["Light vs L — Death Note", []],
    ["Ash vs Gary — Pokémon", []],
    ["Asta vs Yuno — Black Clover", []],
    ["Yugi vs Kaiba — Yu-Gi-Oh!", []],
    ["Thorfinn vs Askeladd — Vinland Saga", []],
  ]),
  build(7, "MOST DISAPPOINTING ANIME ENDING", "Name the anime with the most disappointing ending.", [
    ["Attack on Titan", ["AOT", "Shingeki no Kyojin", "SNK"]],
    ["Jujutsu Kaisen", ["JJK"]],
    ["The Promised Neverland", ["Promised Neverland", "TPN", "Yakusoku no Neverland"]],
    ["Tokyo Revengers", []],
    ["Food Wars!", ["Food Wars", "Shokugeki no Soma"]],
    ["Akame ga Kill!", ["Akame ga Kill"]],
    ["Darling in the Franxx", ["DITF"]],
    ["The Seven Deadly Sins", ["Seven Deadly Sins", "Nanatsu no Taizai", "7DS"]],
    ["Bleach", []],
    ["Naruto", ["Naruto Shippuden"]],
  ]),
  build(8, "ANIME CHARACTER WITH THE BIGGEST IQ / SMARTEST CHARACTER", "Name the smartest anime character.", [
    ["Lelouch — Code Geass", ["Lelouch Lamperouge"]],
    ["Light Yagami — Death Note", ["Light"]],
    ["L — Death Note", ["L Lawliet", "Ryuzaki"]],
    ["Senku — Dr. Stone", ["Senku Ishigami"]],
    ["Shikamaru — Naruto", ["Shikamaru Nara"]],
    ["Johan Liebert — Monster", ["Johan"]],
    ["Ayanokoji — Classroom of the Elite", ["Kiyotaka Ayanokoji", "Ayanokouji"]],
    ["Aizen", ["Sosuke Aizen", "Aizen Sosuke"]],
    ["Kisuke Urahara — Bleach", ["Urahara"]],
    ["Erwin — Attack on Titan", ["Erwin Smith"]],
  ]),
  build(9, "BEST ANIME POWER SYSTEM", "Name the best power system in anime.", [
    ["Nen — Hunter × Hunter", []],
    ["Chakra — Naruto", []],
    ["Devil Fruits/Haki — One Piece", ["Devil Fruits", "Devil Fruit", "Haki"]],
    ["Cursed Energy — Jujutsu Kaisen", ["Cursed Technique", "Cursed Techniques"]],
    ["Stands — JoJo's Bizarre Adventure", ["Stand", "JoJo"]],
    ["Alchemy — Fullmetal Alchemist", []],
    ["Quirks — My Hero Academia", ["Quirk"]],
    ["Bankai/Zanpakutō — Bleach", ["Bankai", "Zanpakuto", "Zanpakutou"]],
    ["Ki — Dragon Ball", []],
    ["Breathing Styles — Demon Slayer", ["Breathing", "Breathing Techniques", "Breath Styles"]],
  ]),
  build(11, "ANIMES THAT MAKE YOU CRY", "Name the answer on the board for this round.", [
    ["Dark Tournament — Yu Yu Hakusho", []],
    ["Chunin Exams — Naruto", ["Chuunin Exams"]],
    ["Heaven's Arena — Hunter × Hunter", []],
    ["World Martial Arts Tournament — Dragon Ball", ["Tenkaichi Budokai"]],
    ["Tournament of Power — Dragon Ball Super", []],
    ["Sports Festival — My Hero Academia", []],
    ["Kengan Annihilation Tournament", ["Kengan Ashura"]],
    ["Kyoto Goodwill Event — Jujutsu Kaisen", ["Kyoto Goodwill"]],
    ["U.A. Sports Festival — My Hero Academia", ["UA Sports Festival"]],
    ["Grand Magic Games — Fairy Tail", []],
  ]),
];
